# ====================================================
# meta.yaml is used to save scenarios indexes,
# 3D object's transform and its corresponding render parameters.
# scale can be a float type num or []
# rotation can be None or [] or [[], ...]
# translate must be [[], ...]
# others can be [] or [[], ...]
# ====================================================
# 1
"0002055":
  model_matrix:
    scale: 0.01
    rotation: [ 0, 0, 0 ]
    translate:
      - [ -1, -0.2, 14 ]
  light:
    ambient_color: [ 105, 109, 109 ]
    diffuse_color: [ 209, 217, 217 ]
    specular_color: [ 0.0, 0.0, 0.0 ]
    location: [ 6, -8, 9 ]

"0002093":
  model_matrix:
    scale: 0.01
    rotation: [ 0, 0, 0 ]
    translate:
      - [ 1, -0.13, 15 ]
  light:
    ambient_color: [ 105, 109, 109 ]
    diffuse_color: [ 188, 195, 195 ]
    specular_color: [ 0.0, 0.0, 0.0 ]
    location: [ 6, -8, 9 ]

"0005057":
  model_matrix:
    scale: 0.01
    rotation: [ 0, 45, 0 ]
    translate:
      - [ -2.5, -0.09, 14.5 ]
  light:
    ambient_color: [ 156, 164, 179 ]
    diffuse_color: [ 120, 120, 120 ]
    specular_color: [ 0.0, 0.0, 0.0 ]
    location: [ 8, -10, 12 ]

"0005181":
  model_matrix:
    scale: 0.01
    rotation: [ 0, 0, 0 ]
    translate:
      - [ 4.5, -0.15, 14 ]
  light:
    ambient_color: [ 145, 152, 167 ]
    diffuse_color: [ 110, 110, 110 ]
    specular_color: [ 0.0, 0.0, 0.0 ]
    location: [ -5, -10, 8 ]

"0014063":
  model_matrix:
    scale: 0.01
    rotation: [ 0, 45, 0 ]
    translate:
      - [ -3, -0.26, 12 ]
  light:
    ambient_color: [ 102, 97, 96 ]
    diffuse_color: [ 204, 194, 191 ]
    specular_color: [ 0.0, 0.0, 0.0 ]
    location: [ -10, -8, 9 ]

"0014196":
  model_matrix:
    scale: 0.01
    rotation: [ 0, 45, 0 ]
    translate:
      - [ 5, -0.20, 14 ]
  light:
    ambient_color: [ 102, 97, 96 ]
    diffuse_color: [ 204, 194, 191 ]
    specular_color: [ 0.0, 0.0, 0.0 ]
    location: [ -5, -8, 10 ]

"0015039":
  model_matrix:
    scale: 0.01
    rotation: [ 0, 0, 0 ]
    translate:
      - [ -2, -0.42, 13.5 ]
  light:
    ambient_color: [ 82, 73, 66 ]
    diffuse_color: [ 204, 182, 165 ]
    specular_color: [ 0.0, 0.0, 0.0 ]
    location: [ 1, 0.5, 11 ]

"0015148":
  model_matrix:
    scale: 0.01
    rotation: [ 0, 0, 0 ]
    translate:
      - [ 1.5, -0.32, 12 ]
  light:
    ambient_color: [ 98, 93, 86 ]
    diffuse_color: [ 163, 156, 142 ]
    specular_color: [ 0.0, 0.0, 0.0 ]
    location: [ -1, 0, 10 ]

"0019016":
  model_matrix:
    scale: 0.01
    rotation: [ 0, 0, 0 ]
    translate:
      - [ -2, -0.03, 14 ]
  light:
    ambient_color: [ 115, 114, 114 ]
    diffuse_color: [ 230, 227, 228 ]
    specular_color: [ 0.0, 0.0, 0.0 ]
    location: [ 6, -8, 10 ]

"0019184":
  model_matrix:
    scale: 0.01
    rotation: [ 0, 0, 0 ]
    translate:
      - [ 3, 0.06, 14 ]
  light:
    ambient_color: [ 115, 114, 114 ]
    diffuse_color: [ 230, 227, 228 ]
    specular_color: [ 0.0, 0.0, 0.0 ]
    location: [ -6, -8, 7 ]

# 2
"0022017":
  model_matrix:
    scale: 0.01
    rotation: [ 0, 45, 0 ]
    translate:
      - [ -3, -0.27, 14 ]
  light:
    ambient_color: [ 167, 170, 182 ]
    diffuse_color: [ 100, 100, 100 ]
    specular_color: [ 0.0, 0.0, 0.0 ]
    location: [ 10, -10, 8 ]

"0022192":
  model_matrix:
    scale: 0.01
    rotation: [ 0, 0, 0 ]
    translate:
      - [ 2, -0.08, 16 ]
  light:
    ambient_color: [ 167, 175, 182 ]
    diffuse_color: [ 100, 100, 100 ]
    specular_color: [ 0.0, 0.0, 0.0 ]
    location: [ 10, -10, 8 ]

"0026091":
  model_matrix:
    scale: 0.01
    rotation: [ 0, 0, 0 ]
    translate:
      - [ -3, -0.22, 14 ]
  light:
    ambient_color: [ 105, 100, 110 ]
    diffuse_color: [ 192, 201, 213 ]
    specular_color: [ 0.0, 0.0, 0.0 ]
    location: [ 10, -8, 8 ]

"0026182":
  model_matrix:
    scale: 0.01
    rotation: [ 0, 45, 0 ]
    translate:
      - [ 2, -0.3, 15 ]
  light:
    ambient_color: [ 105, 100, 110 ]
    diffuse_color: [ 192, 201, 213 ]
    specular_color: [ 0.0, 0.0, 0.0 ]
    location: [ 10, -8, 8 ]

"0029000":
  model_matrix:
    scale: 0.01
    rotation: [ 0, 45, 0 ]
    translate:
      - [ -3, -0.23, 12 ]
  light:
    ambient_color: [ 109, 104, 102 ]
    diffuse_color: [ 217, 207, 203 ]
    specular_color: [ 0.0, 0.0, 0.0 ]
    location: [ -8, -10, 12 ]

"0029077":
  model_matrix:
    scale: 0.01
    rotation: [ 0, 45, 0 ]
    translate:
      - [ 2.5, -0.26, 15 ]
  light:
    ambient_color: [ 109, 104, 102 ]
    diffuse_color: [ 217, 207, 203 ]
    specular_color: [ 0.0, 0.0, 0.0 ]
    location: [ -2, -10, 16 ]

"0032111":
  model_matrix:
    scale: 0.01
    rotation: [ 0, 0, 0 ]
    translate:
      - [ -3, -0.13, 13 ]
  light:
    ambient_color: [ 128, 127, 120 ]
    diffuse_color: [ 217, 215, 200 ]
    specular_color: [ 0.0, 0.0, 0.0 ]
    location: [ 8, -6, 13 ]

"0032144":
  model_matrix:
    scale: 0.01
    rotation: [ 0, 0, 0 ]
    translate:
      - [ 2.5, -0.02, 15 ]
  light:
    ambient_color: [ 128, 127, 120 ]
    diffuse_color: [ 217, 215, 200 ]
    specular_color: [ 0.0, 0.0, 0.0 ]
    location: [ 14, -6, 15 ]

"0050057":
  model_matrix:
    scale: 0.01
    rotation: [ 0, 0, 0 ]
    translate:
      - [ -1, 0.06, 14 ]
  light:
    ambient_color: [ 87, 82, 82 ]
    diffuse_color: [ 253, 245, 245 ]
    specular_color: [ 0.0, 0.0, 0.0 ]
    location: [ 7, -6, 12 ]

"0050126":
  model_matrix:
    scale: 0.01
    rotation: [ 0, 0, 0 ]
    translate:
      - [ 2, -0.05, 14 ]
  light:
    ambient_color: [ 107, 102, 102 ]
    diffuse_color: [ 253, 245, 245 ]
    specular_color: [ 0.0, 0.0, 0.0 ]
    location: [ 7, -6, 14 ]

